### ISSUE TITLE
Needs some help compiling

### ISSUE THREAD

**Issue by POTSandSTOP** [jrbasso/gistit#10]
There seem to be four dependencies for gistit based on the README, two different cURL packages and two different jansson packages.

~~~~
sudo apt-get install libcurl3 libjansson4 libcurl4-openssl-dev libjansson-dev
~~~~

The above packages were successfully installed.

When I get to this step I encounter my first difficulty:

~~~~
$ ./autogen.sh
./autogen.sh: 5: ./autogen.sh: autoreconf: not found
~~~~

Can anyone help?

**Comment by jrbasso** [comment]
You may need to install `autoconf` as well.

```sh
sudo apt-get install autoconf
```

Let me know if that works for you. If so, I will include that in the readme too.

**Comment by POTSandSTOP** [comment]
Hi Juan, thanks for your prompt reply. Installing `autoconf` did allow me to make progress so it should probably be added to the readme, but now I'm running into a problem where `m4` appears to be compiled for a CPU with different features. I tried compiling `m4` from source but no go; I'm not able to continue but it's not the fault of gistit. Thanks for trying to help, though!

~~~~
$ ./autogen.sh
     autoreconf: Entering directory `.'
     autoreconf: configure.in: not using Gettext
     autoreconf: running: aclocal --force ${ACLOCAL_FLAGS}
     aclocal: warning: autoconf input should be named 'configure.ac', not 'configure.in'
     Illegal instruction
     autom4te: need GNU m4 1.4 or later: /usr/bin/m4
     aclocal: error: echo failed with exit status: 1
     autoreconf: aclocal failed with exit status: 1
$
~~~~
