### ISSUE TITLE
"Must specify access token via Authorization header" starting today

### ISSUE THREAD

**Issue by peterbe** [jrbasso/gistit#12]
It's been working great but suddenly today it stopped working. 

```
▶ cat dummy.sql| gistit
Failed to post to GitHub
- code 400
- response {"message":"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"}
```

https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/ says that on "May 5, 2021: For 12 hours starting at 14:00 UTC" it will stop working. Aka. "brownouts". 

I loooove this tool and use it almost every day.

**Comment by peterbe** [comment]
I have...

```
▶ brew info gistit
gistit: stable 0.1.3 (bottled), HEAD
Command-line utility for creating Gists
https://gistit.herokuapp.com/
/usr/local/Cellar/gistit/0.1.3 (5 files, 55.9KB) *
  Poured from bottle on 2021-05-05 at 14:21:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gistit.rb
License: MIT
==> Dependencies
Build: autoconf ✘, automake ✘
Required: jansson ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 1 (30 days), 3 (90 days), 25 (365 days)
install-on-request: 1 (30 days), 3 (90 days), 25 (365 days)
build-error: 0 (30 days)
```

**Comment by jrbasso** [comment]
Glad to hear you are still using gitsit! :)

I will work in this change and release a new version in the next days.

**Comment by jrbasso** [comment]
Hi, I fixed it in the source, generate a new a version and submitted the [new version to homebrew](https://github.com/Homebrew/homebrew-core/pull/76747). Once they approve it will be available for you to update.

**Comment by jrbasso** [comment]
The update is available thru homebrew. You can update by running `brew upgrade gistit`
