### ISSUE TITLE
Copy Gist URL to clipboard

### ISSUE THREAD

**Issue by tomfuertes** [jrbasso/gistit#6]
Something like the 'psuedo'code below would take a few browser opens / clicks / cmd+c's out of the "share this over Skype/Email" use cases.

`echo json_string_value(j_url) | pbcopy`

Sorry for lack of pull request -- I'm a C noob :(

**Comment by robsonpeixoto** [comment]
Please, release a new version with this feature.

**Comment by jrbasso** [comment]
@robsonpeixoto Are you having problems with the latest version? I implemented it almost 2 years ago. To copy to clipboard use `gistit --copy ...`

**Comment by robsonpeixoto** [comment]
@jrbasso I have no problem. But doesn't have a release with this feature: https://github.com/jrbasso/gistit/compare/v0.1.2...master

This feature was implemented after the version v0.1.2

**Comment by jrbasso** [comment]
@robsonpeixoto Thanks for the heads up. I created the v0.1.3 version.
